User.create(full_name: "Mr. Whiskers", user_name: "RadCat900", email: "example@email.com", password: "erinisgreat")
User.create(full_name: "Kitty Purry", user_name: "pussinboots", email: "example@email.com", password: "erinisgreat")
User.create(full_name: "Fluffy McFlufferpants", user_name: "NoK9s", email: "example@email.com", password: "erinisgreat")
User.create(full_name: "Boots", user_name: "fluffybutt", email: "example@email.com", password: "erinisgreat")
User.create(full_name: "Jinx", user_name: "kiTTTTy", email: "example@email.com", password: "erinisgreat")
User.create(full_name: "General Mao", user_name: "catnip420", email: "example@email.com", password: "erinisgreat")
User.create(full_name: "Darrell", user_name: "DarrellIsRad", email: "darrellgarland81@gmail.com", password: "erinisgreat")
User.create(full_name: "Andrew", user_name: "AndrewIsCool", email: "jdrewsdc@gmail.com", password: "erinisgreat")
User.create(full_name: "Nathan", user_name: "NateIsGreat", email: "nsass711@gmail.com", password: "erinisgreat")
User.create(full_name: "Erin", user_name: "ErinIsAwesome", email: "ejcummins@gmail.com", password: "erinisgreat")
